/* eslint-disable max-len */
/* eslint-disable no-console */
// const rand = Math.floor(
//   (Math.random() * 100000000) + 1,
// );
// playerName = "Player" + rand.toString();

// console.log(playerName)

// const scores = [{ score: 496, user: 'Marcelo' },
//   { score: 436, user: 'SunShine' },
//   { user: 'Defender of humanity', score: 396 },
//   { user: 'Unredeemable', score: 336 },
//   { user: 'Ego Provocateur', score: 305 },
//   { score: 292, user: 'Hunter' },
//   { score: 193, user: 'Stream test' },
//   { score: 192, user: 'Time traveler' },
//   { score: 175, user: 'Can you beat me?' },
//   { user: 'Test', score: 156 },
//   { user: 'klASDHLKASDJHFLAKJSDHFLKADJS', score: 155 },
//   { user: 'Test', score: 155 },
//   { user: 'gfh', score: 155 },
//   { score: 154, user: 'Yo!' },
//   { user: 'Can you beat me?', score: 146 },
//   { user: 'Space Warfare God', score: 115 },
//   { user: 'Space Warfare God', score: 111 },
//   { user: 'Marcelo', score: 46 },
//   { user: 'Microverse Test Game', score: 38 },
//   { user: 'Yess', score: 38 },
//   { score: 27, user: 'Test' },
//   { user: 'Defender of humanity', score: 20 },
//   { user: 'sfg', score: 5 },
//   { user: 'Faker', score: 3 },
//   { user: 'Marcelo', score: 3 },
//   { user: 'SunShine', score: 3 },
//   { user: 'Space Warfare God', score: 1 },
//   { user: 'Space Warfare God', score: 1 },
//   { user: 'Space Warfare God', score: 1 },
//   { user: 'Space Warfare God', score: 1 },
//   { user: 'Space Warfare God', score: -3 },
//   { score: -61, user: 'Space Warfare God' },
//   { score: -235, user: 'God' },
//   { score: -366, user: 'God' },
//   { user: 'Player20118199', score: -555 },
//   { score: -555, user: 'Player60623940' },
//   { score: -555, user: 'Player13376713' },
//   { score: -555, user: 'Player48025451' },
//   { score: -555, user: 'Player34744012' },
//   { user: 'Player93948863', score: -555 },
//   { user: 'Player74142932', score: -555 },
//   { user: 'Player20844223', score: -555 },
//   { score: -555, user: 'Player25761112' },
//   { user: 'test', score: -555 },
//   { user: 'Player83904305', score: -555 },
//   { score: -9900, user: 'Space Warfare God' },
//   { user: 'Space Warfare God', score: -9900 },
//   { score: -9989, user: 'Space Warfare God' },
//   { user: 'Space Warfare God', score: -9989 },
//   { user: 'Space Warfare God', score: -9989 },
//   { score: -9989, user: 'Space Warfare God' },
//   { score: -9989, user: 'Space Warfare God' },
//   { user: 'Space Warfare God', score: -9989 },
//   { user: 'Space Warfare God', score: -9989 },
//   { score: -9989, user: 'Space Warfare God' },
//   { user: 'Space Warfare God', score: -9989 },
//   { score: -9989, user: '1Space Warfare God' },
//   { user: 'Space Warfare God', score: -9989 },
//   { user: 'Space Warfare God', score: -9989 },
//   { score: -9989, user: 'Space Warfare God' },
//   { score: -9989, user: 'Space Warfare God' },
//   { score: -9990, user: 'terere' },
//   { score: -9990, user: 'terere' },
//   { score: -9990, user: 'terere' },
//   { user: 'terere', score: -9990 },
//   { user: 'terere', score: -9990 },
//   { score: -9990, user: 'terere' },
//   { user: 'terere', score: -9990 },
//   { score: -9990, user: 'terere' },
//   { user: 'terere', score: -9991 },
//   { user: 'terere', score: -9992 },
//   { score: -9993, user: 'terere' },
//   { score: -9994, user: 'terere' },
//   { user: 'terere', score: -9995 },
//   { score: -9996, user: 'terere' },
//   { user: 'terere', score: -9997 },
//   { user: 'terere', score: -9998 },
//   { user: 'terere', score: -9999 },
//   { score: -9999, user: 'terere' }];

// const result = scores.some(playerScore => playerScore.user === 'terere' && playerScore.score === -9999);
// console.log(result);
